/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as HydrationRouteImport } from './routes/hydration'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BbtRouteImport } from './routes/bbt'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const HydrationRoute = HydrationRouteImport.update({
  id: '/hydration',
  path: '/hydration',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BbtRoute = BbtRouteImport.update({
  id: '/bbt',
  path: '/bbt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bbt': typeof BbtRoute
  '/chat': typeof ChatRoute
  '/faq': typeof FaqRoute
  '/hydration': typeof HydrationRoute
  '/notes': typeof NotesRoute
  '/partner': typeof PartnerRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/tips': typeof TipsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bbt': typeof BbtRoute
  '/chat': typeof ChatRoute
  '/faq': typeof FaqRoute
  '/hydration': typeof HydrationRoute
  '/notes': typeof NotesRoute
  '/partner': typeof PartnerRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/tips': typeof TipsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bbt': typeof BbtRoute
  '/chat': typeof ChatRoute
  '/faq': typeof FaqRoute
  '/hydration': typeof HydrationRoute
  '/notes': typeof NotesRoute
  '/partner': typeof PartnerRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/tips': typeof TipsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/auth'
    | '/bbt'
    | '/chat'
    | '/faq'
    | '/hydration'
    | '/notes'
    | '/partner'
    | '/reminders'
    | '/settings'
    | '/tips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/auth'
    | '/bbt'
    | '/chat'
    | '/faq'
    | '/hydration'
    | '/notes'
    | '/partner'
    | '/reminders'
    | '/settings'
    | '/tips'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/auth'
    | '/bbt'
    | '/chat'
    | '/faq'
    | '/hydration'
    | '/notes'
    | '/partner'
    | '/reminders'
    | '/settings'
    | '/tips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BbtRoute: typeof BbtRoute
  ChatRoute: typeof ChatRoute
  FaqRoute: typeof FaqRoute
  HydrationRoute: typeof HydrationRoute
  NotesRoute: typeof NotesRoute
  PartnerRoute: typeof PartnerRoute
  RemindersRoute: typeof RemindersRoute
  SettingsRoute: typeof SettingsRoute
  TipsRoute: typeof TipsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hydration': {
      id: '/hydration'
      path: '/hydration'
      fullPath: '/hydration'
      preLoaderRoute: typeof HydrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bbt': {
      id: '/bbt'
      path: '/bbt'
      fullPath: '/bbt'
      preLoaderRoute: typeof BbtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BbtRoute: BbtRoute,
  ChatRoute: ChatRoute,
  FaqRoute: FaqRoute,
  HydrationRoute: HydrationRoute,
  NotesRoute: NotesRoute,
  PartnerRoute: PartnerRoute,
  RemindersRoute: RemindersRoute,
  SettingsRoute: SettingsRoute,
  TipsRoute: TipsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
